### ISSUE TITLE
Running the basic trueseeing target.apk command prints the html report in the command line instead of creating an html file.

### ISSUE THREAD

**Issue by JanPana** [alterakey/trueseeing#530]

**Comment by alterakey** [comment]
Hello @JanPana , thank you for your report!
But as I far as I know trueseeing prints the report, instead of writing in a file, on non-interactive scan mode unless --scan-output option is given -- please see https://github.com/alterakey/trueseeing#non-interactive-scan-mode-deprecated .

Could you provide some transcript so I can take a look?
Thank you.
